# Generated by Django 3.1.3 on 2021-02-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('quantity', models.CharField(default=1, max_length=250)),
                ('date_of_creation', models.DateField()),
            ],
        ),
    ]
